apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: test-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      # This container will run as root and has no resource limits
      containers:
        - name: test-container
          image: alpine:latest
          command: ["sleep", "3600"]
          ports:
            - containerPort: 80
          # Privileged mode and hostPath are both common Checkov flags
          securityContext:
            privileged: true
          volumeMounts:
            - name: host-volume
              mountPath: /data
      # hostPath volume (another Checkov “Warning” candidate)
      volumes:
        - name: host-volume
          hostPath:
            path: /tmp
            type: Directory
